//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Scripts/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""PlayerController"",
            ""id"": ""d7e16c76-312c-4fb2-a865-96784211e042"",
            ""actions"": [
                {
                    ""name"": ""JUMP"",
                    ""type"": ""Button"",
                    ""id"": ""4789b4f6-18d4-4640-a8de-03c649eea53d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MOVE"",
                    ""type"": ""Value"",
                    ""id"": ""0f519240-0fa6-44d1-99f0-73b6fc205272"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LOOK"",
                    ""type"": ""Value"",
                    ""id"": ""22298c23-8744-4231-bf43-45d0bb5927e8"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RUN"",
                    ""type"": ""Button"",
                    ""id"": ""739b190e-426b-4ebf-b0b3-d87c7a81eddc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AIM"",
                    ""type"": ""Button"",
                    ""id"": ""b8274eea-1301-4195-ad4b-62dc9119b601"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""INTERACTION"",
                    ""type"": ""Button"",
                    ""id"": ""1cb1c42f-20d0-4135-a2cf-663e67a82db0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SQUAT"",
                    ""type"": ""Button"",
                    ""id"": ""cf5e54d2-6b9b-4283-9f46-1afef4874456"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SHOOT"",
                    ""type"": ""Button"",
                    ""id"": ""3aaa89a3-6542-401f-89a6-a57fa7552ba5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap,Hold(duration=0.2,pressPoint=0.2)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RELOAD"",
                    ""type"": ""Button"",
                    ""id"": ""52600e66-2fb3-4ab1-b26b-dec2c52aac29"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CHANGE_GUNS(WHEEL)"",
                    ""type"": ""PassThrough"",
                    ""id"": ""2b0ed6b5-dea5-41a6-9db6-70af0346b546"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CHANGE_GUNS(GAMEPAD)"",
                    ""type"": ""Value"",
                    ""id"": ""4d029de0-e1c2-4c30-b324-9e743a4471ea"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CHANGE_GUNS_(NUM_DIREC)"",
                    ""type"": ""Value"",
                    ""id"": ""a845a5df-66f4-4c57-96a0-ccfa7f92bddc"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1d23b844-15d5-4b30-887e-1b511b5ce62e"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""JUMP"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""084f0d58-0aa8-464f-8700-3963c34d8634"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""JUMP"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""KEYWORD"",
                    ""id"": ""cb9ceaa4-43e1-4690-b317-78dc25f679c4"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MOVE"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""5a5b36fc-bab1-4f71-8e2c-8065163bfbe5"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""MOVE"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f273d0ae-fd1c-4640-b46c-77c274a5af76"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""MOVE"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""0e2e59ae-73e0-41db-b863-388f8d6d9131"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""MOVE"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""8e28157f-d59d-4c8a-94d0-3d1cace78539"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""MOVE"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""40adf00e-e103-4bfd-9b89-5c000aa07920"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": ""Gamepad"",
                    ""action"": ""MOVE"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c6d7038-247c-40f0-893c-95d0e3986664"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""LOOK"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b51e5e12-94d7-40b4-97f7-d5bbc1cadfdc"",
                    ""path"": ""*/{Hatswitch}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""LOOK"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b9967242-afd9-40f3-8ebc-57bcb86ec231"",
                    ""path"": ""<Pointer>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LOOK"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f4b56650-c312-405c-ba93-cafd6c879afd"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""RUN"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b0cce0d5-23dc-4612-973b-333382e51933"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""RUN"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""340fac81-5d68-4327-bbcc-8c5e8dd02b0d"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""AIM"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2fe3aacb-f69c-4d35-8db9-a53a14623ff1"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""AIM"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5715a5fc-0725-4077-9ea9-7361d401160f"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""INTERACTION"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f4a2288-3370-46f8-94a3-48a0ddaa5472"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""INTERACTION"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9015145d-8d03-444e-b286-0ecaaa1ca1ba"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""SQUAT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a6fb5b7c-bb29-4e18-81bc-90373c5a973e"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""SQUAT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dbc73748-04c7-4be7-8242-fefb778643de"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""SHOOT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5ba9d355-7087-4690-9cc2-7e88f2bbb2e5"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""SHOOT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""663fb95e-7504-43ed-9316-0d4da6f6fe81"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""RELOAD"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e69ef449-1003-4206-a9d3-a0aa19bf0f6c"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""RELOAD"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c84da0b-3f05-44dd-b2d6-4b53e251fde5"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""CHANGE_GUNS(WHEEL)"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""SHOULDERS"",
                    ""id"": ""a300f72b-5a4a-454e-9737-863c2728bab1"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CHANGE_GUNS(GAMEPAD)"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""41ce1c99-3f95-4451-ba9e-4c6cab2659e2"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""CHANGE_GUNS(GAMEPAD)"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""7da22018-8d8c-407d-8125-33681c882df4"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""CHANGE_GUNS(GAMEPAD)"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1_4"",
                    ""id"": ""de960691-7f79-4015-aae1-6b461b4de0d3"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CHANGE_GUNS_(NUM_DIREC)"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Up"",
                    ""id"": ""e410f8a7-c325-4bec-9f4d-ad8740ae6aea"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""CHANGE_GUNS_(NUM_DIREC)"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Down"",
                    ""id"": ""0cb36e38-f27c-4657-9e25-f19439e5c7ae"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""CHANGE_GUNS_(NUM_DIREC)"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Left"",
                    ""id"": ""53bf1359-cc84-45ea-8266-1753e8f5ce54"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""CHANGE_GUNS_(NUM_DIREC)"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Right"",
                    ""id"": ""89d4dba0-eb4b-49cc-9626-8c36b6765cb7"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""CHANGE_GUNS_(NUM_DIREC)"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Direcionais"",
                    ""id"": ""9211cbab-b542-4b93-bf14-26ce566045dd"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CHANGE_GUNS_(NUM_DIREC)"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d74391ff-c3c0-4b57-83f7-d8cde054904b"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CHANGE_GUNS_(NUM_DIREC)"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b9b721c4-be00-4ce1-b580-25a0cf6be76d"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CHANGE_GUNS_(NUM_DIREC)"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""681808c5-1bf2-45b0-b71e-6e90bdbbd2d2"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CHANGE_GUNS_(NUM_DIREC)"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d4cfda77-b668-470a-9a41-1c595f03fb2e"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CHANGE_GUNS_(NUM_DIREC)"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""GameController"",
            ""id"": ""10560963-f006-44c3-9b45-4fd77f8f4d48"",
            ""actions"": [
                {
                    ""name"": ""EXIT"",
                    ""type"": ""Button"",
                    ""id"": ""487bda1a-941f-4aab-a528-b582ec170b29"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""REESTART"",
                    ""type"": ""Button"",
                    ""id"": ""977ccb01-96e5-4269-ac0c-9bf2231a87cb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ab4a6796-d232-413e-bd8e-16ee4e29641c"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""EXIT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6242c027-1f5b-41da-bbe8-94ff4b6158e9"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""EXIT"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""143bed50-7e63-471d-b150-2d54462646e8"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""REESTART"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1d4c6b89-5450-4344-8efc-7f6042307bda"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""REESTART"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8376cb3a-b3f2-4658-a3f5-dbf17fe201be"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""REESTART"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // PlayerController
        m_PlayerController = asset.FindActionMap("PlayerController", throwIfNotFound: true);
        m_PlayerController_JUMP = m_PlayerController.FindAction("JUMP", throwIfNotFound: true);
        m_PlayerController_MOVE = m_PlayerController.FindAction("MOVE", throwIfNotFound: true);
        m_PlayerController_LOOK = m_PlayerController.FindAction("LOOK", throwIfNotFound: true);
        m_PlayerController_RUN = m_PlayerController.FindAction("RUN", throwIfNotFound: true);
        m_PlayerController_AIM = m_PlayerController.FindAction("AIM", throwIfNotFound: true);
        m_PlayerController_INTERACTION = m_PlayerController.FindAction("INTERACTION", throwIfNotFound: true);
        m_PlayerController_SQUAT = m_PlayerController.FindAction("SQUAT", throwIfNotFound: true);
        m_PlayerController_SHOOT = m_PlayerController.FindAction("SHOOT", throwIfNotFound: true);
        m_PlayerController_RELOAD = m_PlayerController.FindAction("RELOAD", throwIfNotFound: true);
        m_PlayerController_CHANGE_GUNSWHEEL = m_PlayerController.FindAction("CHANGE_GUNS(WHEEL)", throwIfNotFound: true);
        m_PlayerController_CHANGE_GUNSGAMEPAD = m_PlayerController.FindAction("CHANGE_GUNS(GAMEPAD)", throwIfNotFound: true);
        m_PlayerController_CHANGE_GUNS_NUM_DIREC = m_PlayerController.FindAction("CHANGE_GUNS_(NUM_DIREC)", throwIfNotFound: true);
        // GameController
        m_GameController = asset.FindActionMap("GameController", throwIfNotFound: true);
        m_GameController_EXIT = m_GameController.FindAction("EXIT", throwIfNotFound: true);
        m_GameController_REESTART = m_GameController.FindAction("REESTART", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerController
    private readonly InputActionMap m_PlayerController;
    private IPlayerControllerActions m_PlayerControllerActionsCallbackInterface;
    private readonly InputAction m_PlayerController_JUMP;
    private readonly InputAction m_PlayerController_MOVE;
    private readonly InputAction m_PlayerController_LOOK;
    private readonly InputAction m_PlayerController_RUN;
    private readonly InputAction m_PlayerController_AIM;
    private readonly InputAction m_PlayerController_INTERACTION;
    private readonly InputAction m_PlayerController_SQUAT;
    private readonly InputAction m_PlayerController_SHOOT;
    private readonly InputAction m_PlayerController_RELOAD;
    private readonly InputAction m_PlayerController_CHANGE_GUNSWHEEL;
    private readonly InputAction m_PlayerController_CHANGE_GUNSGAMEPAD;
    private readonly InputAction m_PlayerController_CHANGE_GUNS_NUM_DIREC;
    public struct PlayerControllerActions
    {
        private @PlayerControls m_Wrapper;
        public PlayerControllerActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @JUMP => m_Wrapper.m_PlayerController_JUMP;
        public InputAction @MOVE => m_Wrapper.m_PlayerController_MOVE;
        public InputAction @LOOK => m_Wrapper.m_PlayerController_LOOK;
        public InputAction @RUN => m_Wrapper.m_PlayerController_RUN;
        public InputAction @AIM => m_Wrapper.m_PlayerController_AIM;
        public InputAction @INTERACTION => m_Wrapper.m_PlayerController_INTERACTION;
        public InputAction @SQUAT => m_Wrapper.m_PlayerController_SQUAT;
        public InputAction @SHOOT => m_Wrapper.m_PlayerController_SHOOT;
        public InputAction @RELOAD => m_Wrapper.m_PlayerController_RELOAD;
        public InputAction @CHANGE_GUNSWHEEL => m_Wrapper.m_PlayerController_CHANGE_GUNSWHEEL;
        public InputAction @CHANGE_GUNSGAMEPAD => m_Wrapper.m_PlayerController_CHANGE_GUNSGAMEPAD;
        public InputAction @CHANGE_GUNS_NUM_DIREC => m_Wrapper.m_PlayerController_CHANGE_GUNS_NUM_DIREC;
        public InputActionMap Get() { return m_Wrapper.m_PlayerController; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerControllerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerControllerActions instance)
        {
            if (m_Wrapper.m_PlayerControllerActionsCallbackInterface != null)
            {
                @JUMP.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnJUMP;
                @JUMP.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnJUMP;
                @JUMP.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnJUMP;
                @MOVE.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnMOVE;
                @MOVE.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnMOVE;
                @MOVE.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnMOVE;
                @LOOK.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnLOOK;
                @LOOK.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnLOOK;
                @LOOK.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnLOOK;
                @RUN.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnRUN;
                @RUN.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnRUN;
                @RUN.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnRUN;
                @AIM.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnAIM;
                @AIM.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnAIM;
                @AIM.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnAIM;
                @INTERACTION.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnINTERACTION;
                @INTERACTION.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnINTERACTION;
                @INTERACTION.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnINTERACTION;
                @SQUAT.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnSQUAT;
                @SQUAT.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnSQUAT;
                @SQUAT.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnSQUAT;
                @SHOOT.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnSHOOT;
                @SHOOT.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnSHOOT;
                @SHOOT.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnSHOOT;
                @RELOAD.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnRELOAD;
                @RELOAD.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnRELOAD;
                @RELOAD.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnRELOAD;
                @CHANGE_GUNSWHEEL.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnCHANGE_GUNSWHEEL;
                @CHANGE_GUNSWHEEL.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnCHANGE_GUNSWHEEL;
                @CHANGE_GUNSWHEEL.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnCHANGE_GUNSWHEEL;
                @CHANGE_GUNSGAMEPAD.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnCHANGE_GUNSGAMEPAD;
                @CHANGE_GUNSGAMEPAD.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnCHANGE_GUNSGAMEPAD;
                @CHANGE_GUNSGAMEPAD.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnCHANGE_GUNSGAMEPAD;
                @CHANGE_GUNS_NUM_DIREC.started -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnCHANGE_GUNS_NUM_DIREC;
                @CHANGE_GUNS_NUM_DIREC.performed -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnCHANGE_GUNS_NUM_DIREC;
                @CHANGE_GUNS_NUM_DIREC.canceled -= m_Wrapper.m_PlayerControllerActionsCallbackInterface.OnCHANGE_GUNS_NUM_DIREC;
            }
            m_Wrapper.m_PlayerControllerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @JUMP.started += instance.OnJUMP;
                @JUMP.performed += instance.OnJUMP;
                @JUMP.canceled += instance.OnJUMP;
                @MOVE.started += instance.OnMOVE;
                @MOVE.performed += instance.OnMOVE;
                @MOVE.canceled += instance.OnMOVE;
                @LOOK.started += instance.OnLOOK;
                @LOOK.performed += instance.OnLOOK;
                @LOOK.canceled += instance.OnLOOK;
                @RUN.started += instance.OnRUN;
                @RUN.performed += instance.OnRUN;
                @RUN.canceled += instance.OnRUN;
                @AIM.started += instance.OnAIM;
                @AIM.performed += instance.OnAIM;
                @AIM.canceled += instance.OnAIM;
                @INTERACTION.started += instance.OnINTERACTION;
                @INTERACTION.performed += instance.OnINTERACTION;
                @INTERACTION.canceled += instance.OnINTERACTION;
                @SQUAT.started += instance.OnSQUAT;
                @SQUAT.performed += instance.OnSQUAT;
                @SQUAT.canceled += instance.OnSQUAT;
                @SHOOT.started += instance.OnSHOOT;
                @SHOOT.performed += instance.OnSHOOT;
                @SHOOT.canceled += instance.OnSHOOT;
                @RELOAD.started += instance.OnRELOAD;
                @RELOAD.performed += instance.OnRELOAD;
                @RELOAD.canceled += instance.OnRELOAD;
                @CHANGE_GUNSWHEEL.started += instance.OnCHANGE_GUNSWHEEL;
                @CHANGE_GUNSWHEEL.performed += instance.OnCHANGE_GUNSWHEEL;
                @CHANGE_GUNSWHEEL.canceled += instance.OnCHANGE_GUNSWHEEL;
                @CHANGE_GUNSGAMEPAD.started += instance.OnCHANGE_GUNSGAMEPAD;
                @CHANGE_GUNSGAMEPAD.performed += instance.OnCHANGE_GUNSGAMEPAD;
                @CHANGE_GUNSGAMEPAD.canceled += instance.OnCHANGE_GUNSGAMEPAD;
                @CHANGE_GUNS_NUM_DIREC.started += instance.OnCHANGE_GUNS_NUM_DIREC;
                @CHANGE_GUNS_NUM_DIREC.performed += instance.OnCHANGE_GUNS_NUM_DIREC;
                @CHANGE_GUNS_NUM_DIREC.canceled += instance.OnCHANGE_GUNS_NUM_DIREC;
            }
        }
    }
    public PlayerControllerActions @PlayerController => new PlayerControllerActions(this);

    // GameController
    private readonly InputActionMap m_GameController;
    private IGameControllerActions m_GameControllerActionsCallbackInterface;
    private readonly InputAction m_GameController_EXIT;
    private readonly InputAction m_GameController_REESTART;
    public struct GameControllerActions
    {
        private @PlayerControls m_Wrapper;
        public GameControllerActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @EXIT => m_Wrapper.m_GameController_EXIT;
        public InputAction @REESTART => m_Wrapper.m_GameController_REESTART;
        public InputActionMap Get() { return m_Wrapper.m_GameController; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameControllerActions set) { return set.Get(); }
        public void SetCallbacks(IGameControllerActions instance)
        {
            if (m_Wrapper.m_GameControllerActionsCallbackInterface != null)
            {
                @EXIT.started -= m_Wrapper.m_GameControllerActionsCallbackInterface.OnEXIT;
                @EXIT.performed -= m_Wrapper.m_GameControllerActionsCallbackInterface.OnEXIT;
                @EXIT.canceled -= m_Wrapper.m_GameControllerActionsCallbackInterface.OnEXIT;
                @REESTART.started -= m_Wrapper.m_GameControllerActionsCallbackInterface.OnREESTART;
                @REESTART.performed -= m_Wrapper.m_GameControllerActionsCallbackInterface.OnREESTART;
                @REESTART.canceled -= m_Wrapper.m_GameControllerActionsCallbackInterface.OnREESTART;
            }
            m_Wrapper.m_GameControllerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @EXIT.started += instance.OnEXIT;
                @EXIT.performed += instance.OnEXIT;
                @EXIT.canceled += instance.OnEXIT;
                @REESTART.started += instance.OnREESTART;
                @REESTART.performed += instance.OnREESTART;
                @REESTART.canceled += instance.OnREESTART;
            }
        }
    }
    public GameControllerActions @GameController => new GameControllerActions(this);
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    public interface IPlayerControllerActions
    {
        void OnJUMP(InputAction.CallbackContext context);
        void OnMOVE(InputAction.CallbackContext context);
        void OnLOOK(InputAction.CallbackContext context);
        void OnRUN(InputAction.CallbackContext context);
        void OnAIM(InputAction.CallbackContext context);
        void OnINTERACTION(InputAction.CallbackContext context);
        void OnSQUAT(InputAction.CallbackContext context);
        void OnSHOOT(InputAction.CallbackContext context);
        void OnRELOAD(InputAction.CallbackContext context);
        void OnCHANGE_GUNSWHEEL(InputAction.CallbackContext context);
        void OnCHANGE_GUNSGAMEPAD(InputAction.CallbackContext context);
        void OnCHANGE_GUNS_NUM_DIREC(InputAction.CallbackContext context);
    }
    public interface IGameControllerActions
    {
        void OnEXIT(InputAction.CallbackContext context);
        void OnREESTART(InputAction.CallbackContext context);
    }
}
